format = "templates/v2"
id = "ad8385a7-9a58-41a5-937f-6e5f1bfef9e4"
tags = [
    "web",
    "hardening",
    "external",
    "config",
]
images = []

[[translations]]
id = "3aeab6d6-b2e5-4905-b43b-f92a8432ac85"
is_main = true
language = "en-US"
status = "finished"

[translations.data]
title = "Session management weaknesses"
cvss = "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:L/I:L/A:N"
summary = """
We were able to identify weaknesses in the web application's session management. 
The users' sessions were usable without time restrictions and therefore did not require re-authentication at any time. 
People with access to a computer system could exploit this situation if another user had not explicitly logged out of the application beforehand.
"""
description = """
We could determine that user sessions were usable without time restrictions. 
This could allow attackers to take over user sessions that were not explicitly logged out beforehand.

This could be possible, for example, by allowing a third person to operate a user's computer in which a session is still active. 
In addition, it could be possible for attackers to reuse session tokens when they become known (e.g. via log files; locally or on proxy servers, etc.).
"""
recommendation = """
* User sessions in web applications should time out automatically after a certain period of inactivity.
* Depending on the criticality of the user authorization and the application, the timeout could be approximately between one hour and one day.
"""
short_recommendation = "Users should be logged out automatically after a certain period of inactivity."
references = []
affected_components = []

[[translations]]
id = "a64b9a96-f657-4e07-b429-02c9507a44f6"
is_main = false
language = "zh-CN"
status = "finished"

[translations.data]
title = "会话管理缺陷"
cvss = "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:L/I:L/A:N"
summary = """
我们在该 Web 应用的会话管理中发现了缺陷。
用户的会话可以不受时间限制地使用，因此在任何时候都无需重新认证。
如果其他用户事先未显式退出应用，能够访问该计算机系统的人员就可能利用这一情况。
"""
description = """
我们发现用户会话可以不受时间限制地使用。
这使攻击者可能接管事先未显式退出的用户会话。

例如，若允许第三人操作仍保有活动会话的用户计算机，就可能出现这种情况。
此外，攻击者还可能在获知会话令牌（Session Token）后对其进行重用（例如通过日志文件：本地或代理服务器上的日志等）。
"""
recommendation = """
* Web 应用中的用户会话应在一定的非活动时间后自动超时。
* 根据用户权限及应用的关键程度，超时时间可大致设置在一小时到一天之间。
"""
short_recommendation = "用户应在一定的非活动时间后被自动注销。"
references = []
affected_components = []
