format = "templates/v2"
id = "0ebd8c6a-6386-4512-b5e5-d2d0b80f19dc"
tags = [
    "infrastructure",
    "external",
]
images = []

[[translations]]
id = "24604e1d-a9c0-46e0-85d3-3674e024721c"
is_main = true
language = "en-US"
status = "finished"

[translations.data]
title = "Untrusted TLS certificates"
cvss = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N"
summary = """
Communication with the application at the transport layer level was not sufficiently protected due to untrusted TLS certificates. 
TLS is used by many protocols to ensure the confidentiality and integrity of communication between two endpoints. 
If web browsers do not trust an application's TLS certificate, the application may be vulnerable to man-in-the-middle attacks 
and thus susceptible to eavesdropping or tampering with traffic. 
Insufficient protection at the transport layer may allow communications between two parties to be compromised by an untrusted third party. 
An attacker could thus obtain sensitive data (e.g., credentials) if necessary. 
In the event of a successful attack, an attacker could gain complete control over all functions 
and data of the application by compromising a privileged user account.
"""
description = """
Transport Layer Security (TLS) is the successor to the now obsolete as well as insecure Secure Sockets Layer (SSL) protocol. 
TLS is a cryptographic protocol developed for secure, encrypted communication between two or more parties. 
The protocol is used in a wide variety of areas, including e-mail, instant messaging, and voice-over-IP. 
The best known use of TLS is on the Web, where it ensures secure communication over HTTPS. 
Primarily, TLS aims to ensure confidentiality, integrity, 
but also authenticity through the use of certificates, between two or more parties.

With TLS, the establishment of a secure connection takes place in several steps. 
Client and server agree on the use of TLS in the first step. 
This is done either by selecting a specific port (e.g. 443 for HTTP) or by making a protocol-specific request to the server (e.g. STARTTLS for SMTP). 
A handshake procedure then begins, in which the client and server negotiate various parameters for the security of the communication link. 
The handshake begins with the client and server agreeing on a respective supported cipher suite, consisting of the symmetric cipher and hash function. 
The server then issues a digital certificate. 
The certificate contains, among other things, the server name, the issuing certificate authority (CA), and the server's data asymmetric key. 
Once the client has verified the validity of the certificate, it generates a symmetric session key for the secure connection. 
This is done either by the client deriving a key from a random number. 
The client encrypts the random number with the server's data key and sends the result to the server. 
The server can use the private key to read the result and also derive the session key. 
However, the client and server could also use the Diffie-Hellman algorithm to securely agree on a random session key. 
Diffie-Hellman also offers the advantage of perfect forward secrecy (PFS). 
PFS prevents subsequent decryption once the server's private key is known. 
Session keys are not exchanged and thus cannot be reconstructed.

The security of TLS-secured communication is based primarily on the trustworthiness of the digital certificate. 
If the trustworthiness is not given, for example because the certificate has expired, 
it contains an incorrect host name or it is a self-signed certificate, no secure key exchange between two endpoints can be guaranteed from the outset. 
In some circumstances, the communication between two parties could be compromised by an untrusted third party in the course of a man-in-the-middle attack. 
For example, an attacker could gain access to sensitive data or inject malicious data into the encrypted data stream to compromise either the client or the server.

We reviewed the TLS certificates of the applications in scope and found untrusted certificates for the following applications:

| host | expired | expiring soon | incorrect host name | incomplete certificate chain | self-signed certificate |
|:---:|:---:|:---:|:---:|:---:|:---:|
| TODO:443 | X | - | - | - | |
"""
recommendation = """
* Acquire new certificates for services that do not have trusted TLS certificates. 
* Generate sufficiently strong asymmetric keys with at least 2048 bits for certificates and protect the private key.
* Use only modern cryptographic hash algorithms such as SHA-256.'
* Make sure that the certificate contains the fully qualified name of the server. The following should also be considered when creating the certificate:
    * Consider whether the "www" subdomain should also be included.
    * Do not include unqualified host names in the certificate.
    * Do not include IP addresses.
    * Do not include internal domain names.
* Create and use wildcard certificates only when there is a real need. Do not use wildcard certificates for convenience.
* Choose an appropriate certificate authority that is trusted by all major browsers. For internal applications, an internal CA can be used. However, ensure that all users have imported the internal CA certificate and thus trust certificates issued by that CA. 
* Check the TLS configuration, including certificates, at regular intervals and adjust as necessary. There are a number of online tools (such as SSLabs, sslyze, etc) that you can use to quickly perform the check.
* For more information and help on TLS certificates, see the linked Transport Layer Protection Cheat Sheet from OWASP.
"""
short_recommendation = """\
Ensure that TLS certificates used are universally valid and trusted. \
Acquire new certificates for the affected services, if necessary. \
Also, follow best practices recommendations for secure TLS server configuration.\
"""
references = [
    "https://cheatsheetseries.owasp.org/cheatsheets/Transport_Layer_Protection_Cheat_Sheet.html",
]
affected_components = []

[[translations]]
id = "cd597411-9fc7-4e16-b6ed-06badecb8cf0"
is_main = false
language = "zh-CN"
status = "finished"

[translations.data]
title = "不受信任的 TLS 证书"
cvss = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N"
summary = """
由于 TLS 证书不受信任，应用在传输层级别的通信未得到充分保护。
TLS 被众多协议用于保障两个端点之间通信的机密性与完整性。
如果 Web 浏览器不信任应用的 TLS 证书，该应用可能容易受到中间人（man-in-the-middle）攻击，
从而导致流量被窃听或篡改。
传输层保护不足可能使双方之间的通信被不受信任的第三方劫持。
攻击者从而可能在必要时获取敏感数据（如登录凭据）。
一旦攻击成功，攻击者还可通过攻陷特权用户账户，获得对应用全部功能和数据的完全控制。
"""
description = """
传输层安全（Transport Layer Security，TLS）是现已过时且不安全的安全套接字层（Secure Sockets Layer，SSL）协议的继任者。
TLS 是一种为两方或多方之间安全、加密通信而开发的密码学协议。
该协议被应用于众多领域，包括电子邮件、即时消息和网络电话（VoIP）。
TLS 最广为人知的用途是在 Web 上通过 HTTPS 保障安全通信。
TLS 的首要目标是在两方或多方之间，借助证书来确保通信的机密性、完整性以及身份真实性。

TLS 建立安全连接的过程分为多个步骤。
第一步，客户端与服务器约定使用 TLS。
这要么通过选用特定端口实现（例如 HTTP 使用 443 端口），要么通过向服务器发送协议特定的请求实现（例如 SMTP 的 STARTTLS）。
随后开始握手过程，客户端与服务器就通信链路安全的各项参数进行协商。
握手开始时，客户端与服务器先就双方均支持的密码套件（cipher suite）达成一致，该套件由对称密码和哈希函数组成。
然后服务器出示数字证书。
证书中包含服务器名称、签发证书的证书颁发机构（CA）以及服务器的非对称公钥等信息。
客户端验证证书有效后，便为安全连接生成一个对称会话密钥。
具体方式可以是客户端从一个随机数派生出密钥：
客户端用服务器的公钥加密该随机数，并将结果发送给服务器。
服务器使用私钥即可读取该结果，同样派生出会话密钥。
此外，客户端与服务器也可以使用 Diffie-Hellman 算法安全地协商出一个随机会话密钥。
Diffie-Hellman 还具备完美前向保密（Perfect Forward Secrecy，PFS）的优势。
即使服务器的私钥日后泄露，PFS 也能防止通信被事后解密。
会话密钥不会被交换，因而无法被重建。

TLS 保护下通信的安全性主要建立在数字证书的可信性之上。
如果可信性不成立，例如证书已过期、包含错误的主机名或是自签名证书，
从一开始就无法保证两个端点之间的安全密钥交换。
在某些情况下，双方之间的通信可能在中间人攻击过程中被不受信任的第三方劫持。
例如，攻击者可能获取敏感数据，或向加密数据流中注入恶意数据，以攻陷客户端或服务器。

我们审查了测试范围内各应用的 TLS 证书，发现以下应用使用了不受信任的证书：

| 主机 | 已过期 | 即将到期 | 主机名错误 | 证书链不完整 | 自签名证书 |
|:---:|:---:|:---:|:---:|:---:|:---:|
| TODO:443 | X | - | - | - | |
"""
recommendation = """
* 为没有受信任 TLS 证书的服务获取新证书。
* 为证书生成至少 2048 位的足够强度的非对称密钥，并妥善保护私钥。
* 仅使用现代密码学哈希算法，如 SHA-256。
* 确保证书包含服务器的完全限定域名（FQDN）。创建证书时还应考虑以下几点：
    * 考虑是否将 “www” 子域名一并纳入。
    * 不要在证书中包含非限定的主机名（unqualified host name）。
    * 不要包含 IP 地址。
    * 不要包含内部域名。
* 仅在确有需要时才创建和使用通配符证书，不要为了图方便而使用通配符证书。
* 选择受所有主流浏览器信任的合适证书颁发机构。对于内部应用，可以使用内部 CA，但要确保所有用户均已导入该内部 CA 的证书，从而信任其签发的证书。
* 定期检查 TLS 配置（包括证书），并按需调整。有多种在线工具（如 SSLabs、sslyze 等）可用于快速完成检查。
* 有关 TLS 证书的更多信息和帮助，请参阅 OWASP 的 Transport Layer Protection Cheat Sheet（见参考资料）。
"""
short_recommendation = """\
确保所使用的 TLS 证书普遍有效且受信任；\
必要时为受影响的服务获取新证书，\
并遵循安全 TLS 服务器配置的最佳实践建议。\
"""
references = [
    "https://cheatsheetseries.owasp.org/cheatsheets/Transport_Layer_Protection_Cheat_Sheet.html",
]
affected_components = []

